name: Generate ASCII Network

on:
  push
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      - run: mkdir -p path/to/artifact

      - name: Execute Cowsay command
        run: cowsay -f dragon "Run to the cover/...." >> path/to/artifact/dragon.txt
      - name: Upload Dragon.txt file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-text-file
          path: path/to/artifact/dragon.txt
        
  test_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
      - name: Download Dragon.txt file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file  
          path: path/to/artifact/dragon.txt
      - name: Test file exists
        run: find . -type f -iname "dragon*"

  deploy_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat path/to/artifact/dragon.txt
      - name: Deploy job
        run: echo "deploying ....."
