name: Generate ASCII Network

on:
  push
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay command
        run: cowsay -f lion "I am king of the jungle" >> lion.txt
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Test file exists
        run: grep -i "lion" lion.txt

  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat lion.txt
      - name: Deploy job
        run: echo "deploying ....."
